In [1]:
import numpy as np

In [2]:
activity = np.load(r'D:\Ali_Thesis\synthetic_data_generation\Data\Process_canada_data\Activities_probs\trial_3_scipy_resample\P13_one_hot_labels.npy')
activity.shape

(417840, 6)

In [3]:
agitation = np.load(r'D:\Ali_Thesis\synthetic_data_generation\Data\Process_canada_data\Activities_probs\trial_3_scipy_resample\P13_agitation.npz')['arr_0']
agitation.shape

(417840,)

In [4]:
activity.dtype, agitation.dtype

(dtype('float64'), dtype('int32'))

In [5]:
activity[0], agitation[0]

(array([0., 0., 0., 0., 1., 0.]), np.int32(0))

In [6]:
activity = activity.astype(np.float32)
agitation = agitation.astype(np.float32)
activity.dtype, activity[0], agitation.dtype, agitation[0]

(dtype('float32'),
 array([0., 0., 0., 0., 1., 0.], dtype=float32),
 dtype('float32'),
 np.float32(0.0))

In [7]:
agitation = agitation.reshape(agitation.shape[0], 1)
agitation.shape

(417840, 1)

In [8]:
labels = np.concatenate((activity, agitation), axis=1)
labels.shape

(417840, 7)

In [9]:
labels[0]

array([0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [10]:
np.savez_compressed('P13_conditions_onehot.npz', labels)