In [1]:
import numpy as np
from tensorflow.keras.utils import to_categorical

In [2]:
activity = np.load(r'D:\Ali_Thesis\synthetic_data_generation\Data\Process_canada_data\Activities_probs\trial_3_scipy_resample\P13_classifications.npz')['array']
activity.shape

(417840,)

In [3]:
agitation = np.load(r'D:\Ali_Thesis\synthetic_data_generation\Data\Process_canada_data\Activities_probs\trial_3_scipy_resample\P13_agitation.npz')['arr_0']
agitation.shape

(417840,)

In [4]:
np.unique(activity)

array([0, 1, 2, 4, 8, 9])

In [5]:
activity[:20]

array([8, 8, 4, 4, 8, 4, 8, 4, 0, 4, 4, 4, 0, 8, 4, 4, 4, 4, 4, 4])

In [6]:
# Map non-sequential labels to sequential indices
unique_labels = np.unique(activity)  # [0, 1, 2, 4, 8, 9]
label_map = {label: idx for idx, label in enumerate(unique_labels)}  
mapped_labels = np.array([label_map[label] for label in activity])
mapped_labels[:20]

array([4, 4, 3, 3, 4, 3, 4, 3, 0, 3, 3, 3, 0, 4, 3, 3, 3, 3, 3, 3])

In [7]:
np.unique(mapped_labels)

array([0, 1, 2, 3, 4, 5])

In [8]:
# Apply one-hot encoding
one_hot_labels = to_categorical(mapped_labels)

In [9]:
# Print results
print("Original Labels:", activity[:20])
print("Mapped Labels:", mapped_labels[:20])
print("One-Hot Encoded Labels:\n", one_hot_labels[:20])

Original Labels: [8 8 4 4 8 4 8 4 0 4 4 4 0 8 4 4 4 4 4 4]
Mapped Labels: [4 4 3 3 4 3 4 3 0 3 3 3 0 4 3 3 3 3 3 3]
One-Hot Encoded Labels:
 [[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [10]:
one_hot_labels.shape, one_hot_labels[0]

((417840, 6), array([0., 0., 0., 0., 1., 0.]))

In [11]:
np.save('P13_one_hot_labels.npy', one_hot_labels)