In [1]:
import numpy as np
import h5py

In [2]:
with h5py.File(r'P13_5_sec_30hz_sequences.h5', 'r') as h5file:
    # List all channel datasets
    P13_5_30hz = h5file['data'][:]

In [3]:
def save_h5(filepath, dataset_name, data):
        """
        Save data to an .h5 file.

        Parameters:
        - filepath (str): Path to the .h5 file.
        - dataset_name (str): Name of the dataset to save.
        - data (numpy.ndarray): Data to save.
        """
        with h5py.File(filepath, 'w') as h5file:
            h5file.create_dataset('data', data=data, compression='gzip', compression_opts=9)
        print(f"Data saved to {filepath} under dataset '{dataset_name}'")

In [3]:
P13_5_30hz_sensor_data = P13_5_30hz[:,2:5,:]
P13_5_30hz_sensor_data[0,:,0], P13_5_30hz_sensor_data.min(), P13_5_30hz_sensor_data.max()

(array([-0.50025874,  0.15633085,  0.82855353]),
 np.float64(-2.9060969321579),
 np.float64(3.24308436153658))

In [4]:
P13_5_30hz.shape

(417840, 8, 150)

In [5]:
P13_5_30hz[0,:,0]

array([ 3.51650000e+13,  1.46143251e-01, -5.00258735e-01,  1.56330855e-01,
        8.28553530e-01,  1.36300000e+01,  3.30722342e+01,  0.00000000e+00])

In [7]:
P13_5_30hz_sensor_data = P13_5_30hz[:,1:7,:]
P13_5_30hz_sensor_data[0,:,0]

array([ 0.14614325, -0.50025874,  0.15633085,  0.82855353, 13.63      ,
       33.07223421])

In [8]:
P13_5_30hz_sensor_data.shape

(417840, 6, 150)

In [9]:
save_h5('P13_5_sec_30hz_sequences_sensor_data.h5', 'data', P13_5_30hz_sensor_data)

Data saved to P13_5_sec_30hz_sequences_sensor_data.h5 under dataset 'data'


In [12]:
P13_agitation_label = P13_5_30hz[:,7,:]
P13_agitation_label.shape

(417840, 150)

In [13]:
P13_agitation_label[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
P13_agitation = (P13_agitation_label.sum(axis=1) > (P13_agitation_label.shape[1] // 2)).astype(int)

In [15]:
P13_agitation.shape

(417840,)

In [16]:
P13_agitation[0]

0

In [17]:
unique_values = np.unique(P13_agitation)
unique_values

array([0, 1])

In [8]:
results = np.load('P13_classifications.npz')

In [18]:
np.savez_compressed('P13_agitation.npz', P13_agitation)

In [9]:
results = results['array']

In [10]:
results[0:10]

array([8, 8, 3, 3, 3, 0, 3, 3, 8, 3])

In [11]:
results.shape

(417840,)

In [7]:
unique, counts = np.unique(results, return_counts=True)

print(f'Unique Values: {unique}')
print(f'Counts: {counts}')

Unique Values: [0 3 5 8]
Counts: [ 75673 209192   2687 130288]


In [8]:
Label_Mapping={'Everyday Household and Childcare Activities': 0, 'Food Preparation and Eating': 1, 'High-Energy Sports/Gym': 2, 'High-Intensity Activities': 3, 'Laundry and Clothing Activities': 4, 'Leisure and Recreational Activities': 5, 'Low-Intensity Walking and Standing Activities': 6, 'Moderate Sports/Gym Activities': 7, 'Rest and Relaxation': 8, 'Sedentary Activities': 9}
Label_Mapping

{'Everyday Household and Childcare Activities': 0,
 'Food Preparation and Eating': 1,
 'High-Energy Sports/Gym': 2,
 'High-Intensity Activities': 3,
 'Laundry and Clothing Activities': 4,
 'Leisure and Recreational Activities': 5,
 'Low-Intensity Walking and Standing Activities': 6,
 'Moderate Sports/Gym Activities': 7,
 'Rest and Relaxation': 8,
 'Sedentary Activities': 9}